# Generated by Django 6.0.5 on 2026-06-19 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_paypal_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='emailsent',
            field=models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failure', 'Failure')], default='pending', max_length=20),
        ),
    ]
