# Generated by Django 6.0.5 on 2026-05-31 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_navigationlinks'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NavigationLinks',
        ),
    ]
