# Generated by Django 6.0.5 on 2026-06-08 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_announcement'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_1', models.TextField(blank=True, null=True)),
                ('image_2', models.TextField(blank=True, null=True)),
                ('image_3', models.TextField(blank=True, null=True)),
                ('image_4', models.TextField(blank=True, null=True)),
                ('image_5', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
